modLoader = "javafml"
loaderVersion = "[${loader_version},)"
issueTrackerURL = "https://github.com/Infinituum17/FastConfigAPI/issues"
license = "Infinituum License v.1.0"

[[mods]]
modId = "fastconfigapi"
version = "${version}"
displayName = "Fast Config API"
authors = "Infinituum"
description = '''
A mod that makes creating Configs easy and fast
'''
logoFile = "assets/fastconfigapi/icon.png"

[[dependencies.fastconfigapi]]
modId = "neoforge"
type = "required"
versionRange = "[${neoforge_base_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.fastconfigapi]]
modId = "minecraft"
mandatory = true
versionRange = "[${minecraft_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.fastconfigapi]]
modId = "void_lib"
mandatory = true
versionRange = "[${void_lib_version},)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "fastconfigapi-common.mixins.json"